import darkTokens from 'design/dist/dark/index.json'
import lightTokens from 'design/dist/light/index.json'
import tokens from 'design/dist/tokens.json'

/**
 * Primitive Color values
 * These are the palette that all themes pull from
 */
export const primitiveColors = {
	transparent: 'rgba(255,255,255,0)',
	inherit: 'inherit',
	white: '#fff',
	black: '#0e0e10',

	bai_pearl0: tokens.color.core.bai_pearl['0'],
	bai_pearl100: tokens.color.core.bai_pearl['100'],
	bai_pearl200: tokens.color.core.bai_pearl['200'],
	bai_pearl300: tokens.color.core.bai_pearl['300'],
	bai_pearl400: tokens.color.core.bai_pearl['400'],
	bai_pearl500: tokens.color.core.bai_pearl['500'],
	bai_pearl600: tokens.color.core.bai_pearl['600'],
	bai_pearl700: tokens.color.core.bai_pearl['700'],
	bai_pearl800: tokens.color.core.bai_pearl['800'],
	bai_pearl900: tokens.color.core.bai_pearl['900'],
	bai_pearl1000: tokens.color.core.bai_pearl['1000'],

	bleached_silk0: tokens.color.core.bleached_silk['0'],
	bleached_silk100: tokens.color.core.bleached_silk['100'],
	bleached_silk200: tokens.color.core.bleached_silk['200'],
	bleached_silk300: tokens.color.core.bleached_silk['300'],
	bleached_silk400: tokens.color.core.bleached_silk['400'],
	bleached_silk500: tokens.color.core.bleached_silk['500'],
	bleached_silk600: tokens.color.core.bleached_silk['600'],
	bleached_silk700: tokens.color.core.bleached_silk['700'],
	bleached_silk800: tokens.color.core.bleached_silk['800'],
	bleached_silk900: tokens.color.core.bleached_silk['900'],
	bleached_silk1000: tokens.color.core.bleached_silk['1000'],

	wax0: tokens.color.core.wax['0'],
	wax100: tokens.color.core.wax['100'],
	wax200: tokens.color.core.wax['200'],
	wax300: tokens.color.core.wax['300'],
	wax400: tokens.color.core.wax['400'],
	wax500: tokens.color.core.wax['500'],
	wax600: tokens.color.core.wax['600'],
	wax700: tokens.color.core.wax['700'],
	wax800: tokens.color.core.wax['800'],
	wax900: tokens.color.core.wax['900'],
	wax1000: tokens.color.core.wax['1000'],

	lead0: tokens.color.core.lead['0'],
	lead100: tokens.color.core.lead['100'],
	lead200: tokens.color.core.lead['200'],
	lead300: tokens.color.core.lead['300'],
	lead400: tokens.color.core.lead['400'],
	lead500: tokens.color.core.lead['500'],
	lead600: tokens.color.core.lead['600'],
	lead700: tokens.color.core.lead['700'],
	lead800: tokens.color.core.lead['800'],
	lead900: tokens.color.core.lead['900'],
	lead1000: tokens.color.core.lead['1000'],

	purple0: tokens.color.core.purple['0'],
	purple100: tokens.color.core.purple['100'],
	purple200: tokens.color.core.purple['200'],
	purple300: tokens.color.core.purple['300'],
	purple400: tokens.color.core.purple['400'],
	purple500: tokens.color.core.purple['500'],
	purple600: tokens.color.core.purple['600'],
	purple700: tokens.color.core.purple['700'],
	purple800: tokens.color.core.purple['800'],
	purple900: tokens.color.core.purple['900'],
	purple1000: tokens.color.core.purple['1000'],

	blue_magenta0: tokens.color.core.blue_magenta['0'],
	blue_magenta100: tokens.color.core.blue_magenta['100'],
	blue_magenta200: tokens.color.core.blue_magenta['200'],
	blue_magenta300: tokens.color.core.blue_magenta['300'],
	blue_magenta400: tokens.color.core.blue_magenta['400'],
	blue_magenta500: tokens.color.core.blue_magenta['500'],
	blue_magenta600: tokens.color.core.blue_magenta['600'],
	blue_magenta700: tokens.color.core.blue_magenta['700'],
	blue_magenta800: tokens.color.core.blue_magenta['800'],
	blue_magenta900: tokens.color.core.blue_magenta['900'],
	blue_magenta1000: tokens.color.core.blue_magenta['1000'],

	red0: tokens.color.core.red['0'],
	red100: tokens.color.core.red['100'],
	red200: tokens.color.core.red['200'],
	red300: tokens.color.core.red['300'],
	red400: tokens.color.core.red['400'],
	red500: tokens.color.core.red['500'],
	red600: tokens.color.core.red['600'],
	red700: tokens.color.core.red['700'],
	red800: tokens.color.core.red['800'],
	red900: tokens.color.core.red['900'],
	red1000: tokens.color.core.red['1000'],

	yellow0: tokens.color.core.yellow['0'],
	yellow100: tokens.color.core.yellow['100'],
	yellow200: tokens.color.core.yellow['200'],
	yellow300: tokens.color.core.yellow['300'],
	yellow400: tokens.color.core.yellow['400'],
	yellow500: tokens.color.core.yellow['500'],
	yellow600: tokens.color.core.yellow['600'],
	yellow700: tokens.color.core.yellow['700'],
	yellow800: tokens.color.core.yellow['800'],
	yellow900: tokens.color.core.yellow['900'],
	yellow1000: tokens.color.core.yellow['1000'],

	orange0: tokens.color.core.orange['0'],
	orange100: tokens.color.core.orange['100'],
	orange200: tokens.color.core.orange['200'],
	orange300: tokens.color.core.orange['300'],
	orange400: tokens.color.core.orange['400'],
	orange500: tokens.color.core.orange['500'],
	orange600: tokens.color.core.orange['600'],
	orange700: tokens.color.core.orange['700'],
	orange800: tokens.color.core.orange['800'],
	orange900: tokens.color.core.orange['900'],
	orange1000: tokens.color.core.orange['1000'],

	green0: tokens.color.core.green['0'],
	green100: tokens.color.core.green['100'],
	green200: tokens.color.core.green['200'],
	green300: tokens.color.core.green['300'],
	green400: tokens.color.core.green['400'],
	green500: tokens.color.core.green['500'],
	green600: tokens.color.core.green['600'],
	green700: tokens.color.core.green['700'],
	green800: tokens.color.core.green['800'],
	green900: tokens.color.core.green['900'],
	green1000: tokens.color.core.green['1000'],
}

/**
 * Light Theme Variable Semantic (Core) colors
 */
export const lightThemeColors = {
	colorNeutral: lightTokens.color.font.neutral.value,
	colorStrong: lightTokens.color.font.strong.value,
	colorInverse: lightTokens.color.font.inverse.value,
	backgroundWallet: 'linear-gradient(180deg, #ded2ff 13.83%, #fbfaff 100%)',
	backgroundPrimary: lightTokens.color.background.primary.value,
	backgroundSecondary: lightTokens.color.background.secondary.value,
	backgroundOverlayPrimary: lightTokens.color.background.overlay_primary.value,
	borderDivider: lightTokens.color.border.divider_primary.value,
	borderDividerSecondary: lightTokens.color.border.divider_secondary.value,
	shadowDropdown: lightTokens.color.shadow.dropdown.value,
	shadowDropdownFocusVisible: lightTokens.color.shadow.dropdownFocusVisible.value,
	shadowScrollTop: lightTokens.color.shadow.shadow_scroll_top.value,
	shadowScrollBottom: lightTokens.color.shadow.shadow_scroll_bottom.value,
	shadowTooltip: lightTokens.color.shadow.shadow_tooltip.value,
	shadowPanel: lightTokens.color.shadow.shadow_panel.value,
	shadowActivePanel: lightTokens.color.shadow.shadow_active_panel.value,
	shadowAccordionOpen: lightTokens.color.shadow.shadow_accordion_open.value,
	btnSecondaryBackground: lightTokens.color.background.btn_secondary_background.value,
	btnSecondaryBackgroundHover: lightTokens.color.background.btn_secondary_background_hover.value,
	btnWhiteTransparentBackgroundHover: lightTokens.color.background.btn_white_transparent_background_hover.value,
	btnSecondaryShadowHover: lightTokens.color.shadow.button_secondary_hover.value,
	btnSecondaryShadowActive: lightTokens.color.shadow.button_secondary_active.value,
	btnSecondaryShadowFocus: lightTokens.color.shadow.button_secondary_focus.value,
	btnSecondaryBorderColor: lightTokens.color.border.btn_secondary_border.value,
	btnSecondaryBorderColorHover: lightTokens.color.border.btn_secondary_border_hover.value,
	btnAvatarShadowHover: lightTokens.color.shadow.button_avatar_hover.value,
	btnAvatarShadowFocus: lightTokens.color.shadow.button_avatar_focus.value,
	btnTertiaryBackground: lightTokens.color.background.btn_tertiary_background.value,
	btnTertiaryBackgroundHover: lightTokens.color.background.btn_tertiary_background_hover.value,
	btnTertiaryBorderColor: lightTokens.color.border.btn_tertiary_border.value,
	btnTertiaryBorderColorHover: lightTokens.color.border.btn_tertiary_border_hover.value,
	btnInverseBackground: lightTokens.color.background.btn_inverse_background.value,
	btnInverseBackgroundHover: lightTokens.color.background.btn_inverse_background_hover.value,
	btnGhostBorderColor: lightTokens.color.border.btn_ghost_border.value,
	btnGhostBorderColorHover: lightTokens.color.border.btn_ghost_border_hover.value,
	inputPrimaryBackground: lightTokens.color.background.input_primary_background.value,
	inputPrimaryBackgroundHover: lightTokens.color.background.input_primary_background_hover.value,
	inputPrimaryBackgroundFocus: lightTokens.color.background.input_primary_background_hover.value,
	inputPrimaryBorderColor: lightTokens.color.border.input_primary_border.value,
	inputPrimaryBorderHover: lightTokens.color.border.input_primary_border_hover.value,
	inputPrimaryBorderFocus: lightTokens.color.border.input_primary_border_focus.value,
	inputPrimaryShadowFocus: lightTokens.color.shadow.input_primary_focus.value,
	inputSecondaryBackground: lightTokens.color.background.input_secondary_background.value,
	inputSecondaryBackgroundHover: lightTokens.color.background.input_secondary_background_hover.value,
	inputSecondaryBackgroundFocus: lightTokens.color.background.input_secondary_background_hover.value,
	inputSecondaryBorderColor: lightTokens.color.border.input_secondary_border.value,
	inputSecondaryBorderHover: lightTokens.color.border.input_secondary_border_hover.value,
	inputSecondaryBorderFocus: lightTokens.color.border.input_secondary_border_focus.value,
	inputSecondaryShadowFocus: lightTokens.color.shadow.input_secondary_focus.value,
	scrollbar: lightTokens.color.scrollbar.track.value,
	scrollbarThumb: lightTokens.color.scrollbar.thumb.value,
	scrollbarThumbHover: lightTokens.color.scrollbar.thumb_hover.value,
	scrollbarThumbActive: lightTokens.color.scrollbar.thumb_active.value,
}

/**
 * Dark Theme Variable Semantic (Core) colors
 */
export const darkThemeColors = {
	colorNeutral: darkTokens.color.font.neutral.value,
	colorStrong: darkTokens.color.font.strong.value,
	colorInverse: darkTokens.color.font.inverse.value,
	backgroundWallet: 'linear-gradient(180deg, #1F1F1F 13.83%, #8457FF 100%)',
	backgroundPrimary: darkTokens.color.background.primary.value,
	backgroundSecondary: darkTokens.color.background.secondary.value,
	backgroundOverlayPrimary: darkTokens.color.background.overlay_primary.value,
	borderDivider: darkTokens.color.border.divider_primary.value,
	borderDividerSecondary: darkTokens.color.border.divider_secondary.value,
	shadowDropdown: darkTokens.color.shadow.dropdown.value,
	shadowDropdownFocusVisible: darkTokens.color.shadow.dropdownFocusVisible.value,
	shadowScrollTop: darkTokens.color.shadow.shadow_scroll_top.value,
	shadowScrollBottom: darkTokens.color.shadow.shadow_scroll_bottom.value,
	shadowTooltip: darkTokens.color.shadow.shadow_tooltip.value,
	shadowPanel: darkTokens.color.shadow.shadow_panel.value,
	shadowActivePanel: darkTokens.color.shadow.shadow_active_panel.value,
	shadowAccordionOpen: darkTokens.color.shadow.shadow_accordion_open.value,
	btnSecondaryBackground: darkTokens.color.background.btn_secondary_background.value,
	btnSecondaryBackgroundHover: darkTokens.color.background.btn_secondary_background_hover.value,
	btnWhiteTransparentBackgroundHover: darkTokens.color.background.btn_white_transparent_background_hover.value,
	btnSecondaryShadowHover: darkTokens.color.shadow.button_secondary_hover.value,
	btnSecondaryShadowActive: darkTokens.color.shadow.button_secondary_active.value,
	btnSecondaryShadowFocus: darkTokens.color.shadow.button_secondary_focus.value,
	btnSecondaryBorderColor: darkTokens.color.border.btn_secondary_border.value,
	btnSecondaryBorderColorHover: darkTokens.color.border.btn_secondary_border_hover.value,
	btnAvatarShadowHover: darkTokens.color.shadow.button_avatar_hover.value,
	btnAvatarShadowFocus: darkTokens.color.shadow.button_avatar_focus.value,
	btnTertiaryBackground: darkTokens.color.background.btn_tertiary_background.value,
	btnTertiaryBackgroundHover: darkTokens.color.background.btn_tertiary_background_hover.value,
	btnTertiaryBorderColor: darkTokens.color.border.btn_tertiary_border.value,
	btnTertiaryBorderColorHover: darkTokens.color.border.btn_tertiary_border_hover.value,
	btnInverseBackground: darkTokens.color.background.btn_inverse_background.value,
	btnInverseBackgroundHover: darkTokens.color.background.btn_inverse_background_hover.value,
	btnGhostBorderColor: darkTokens.color.border.btn_ghost_border.value,
	btnGhostBorderColorHover: darkTokens.color.border.btn_ghost_border_hover.value,
	inputPrimaryBackground: darkTokens.color.background.input_primary_background.value,
	inputPrimaryBackgroundHover: darkTokens.color.background.input_primary_background_hover.value,
	inputPrimaryBackgroundFocus: darkTokens.color.background.input_primary_background_hover.value,
	inputPrimaryBorderColor: darkTokens.color.border.input_primary_border.value,
	inputPrimaryBorderHover: darkTokens.color.border.input_primary_border_hover.value,
	inputPrimaryBorderFocus: darkTokens.color.border.input_primary_border_focus.value,
	inputPrimaryShadowFocus: darkTokens.color.shadow.input_primary_focus.value,
	inputSecondaryBackground: darkTokens.color.background.input_secondary_background.value,
	inputSecondaryBackgroundHover: darkTokens.color.background.input_secondary_background_hover.value,
	inputSecondaryBackgroundFocus: darkTokens.color.background.input_secondary_background_hover.value,
	inputSecondaryBorderColor: darkTokens.color.border.input_secondary_border.value,
	inputSecondaryBorderHover: darkTokens.color.border.input_secondary_border_hover.value,
	inputSecondaryBorderFocus: darkTokens.color.border.input_secondary_border_focus.value,
	inputSecondaryShadowFocus: darkTokens.color.shadow.input_secondary_focus.value,
	scrollbar: darkTokens.color.scrollbar.track.value,
	scrollbarThumb: darkTokens.color.scrollbar.thumb.value,
	scrollbarThumbHover: darkTokens.color.scrollbar.thumb_hover.value,
	scrollbarThumbActive: darkTokens.color.scrollbar.thumb_active.value,
}
