name: extension - test
on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'apps/extension/**'
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'apps/extension/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Copy Files
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 15.5.0
      - name: Print Node version
        run: node -v
      - name: Print yarn version
        run: yarn -v
      - name: Install dependencies
        run: |-
          cd apps/extension
          yarn --ignore-engines
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
      - name: Run build
        run: |-
          cd apps/extension
          yarn build
      - name: Run headful puppeteer tests
        uses: djp3/puppeteer-headful@master
        with:
          node-version: 15.5.0
          yarn-version: 1.22.10
        with:
          args: yarn e2e --ignore-engines
